const test = require('node:test');
const assert = require('node:assert/strict');
const database = require('./database');
const prisma = database.prisma;
const http = require('node:http');
const { randomBytes } = require('node:crypto');

test('accounts protect all business data, activate staff, enforce roles and revoke sessions', async t => {
  process.env.NODE_ENV = 'test';
  const app = require('../server');
  await database.setup(t);

  const server = http.createServer(app);
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(async () => { await new Promise(resolve => server.close(resolve));  });
  const base = `http://127.0.0.1:${server.address().port}`;
  async function call(path, method = 'GET', body, cookie, origin) {
    const response = await fetch(base + path, { method, headers: { 'Content-Type': 'application/json', ...(cookie ? { Cookie: cookie } : {}), ...(origin ? { Origin: origin } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
    return { status: response.status, data: await response.json(), cookies: response.headers.getSetCookie() };
  }
  const cookieOf = response => response.cookies.find(c => c.startsWith('stonedesk_session=') && !c.startsWith('stonedesk_session=;')).split(';')[0];
  for (const path of ['/api/dispatches', '/api/loading-lists', '/api/master-settings/unit_04', '/uploads/unknown.png']) assert.equal((await call(path)).status, 401);
  const password = randomBytes(18).toString('hex');
  assert.equal((await call('/api/auth/signup', 'POST', { email: 'a@example.test', password: 'short', name: 'Owner' })).status, 400);
  assert.equal((await call('/api/auth/signup', 'POST', { email: 'owner@example.test', password, name: 'Owner' }, null, 'https://untrusted.example')).status, 403);
  const accounts = await Promise.all(['one', 'two'].map(name => call('/api/auth/signup', 'POST', { email: `${name}@example.test`, name, password, role: 'Admin', active: true })));
  assert.ok(accounts.every(a => a.status === 201));
  assert.equal(accounts.filter(a => a.data.user.active).length, 2);
  assert.equal(await prisma.user.count({ where: { role: 'Admin' } }), 1);
  const owner = accounts.find(a => a.data.user.isOwner), staff = accounts.find(a => !a.data.user.isOwner);
  const ownerCookie = cookieOf(owner); let staffCookie = cookieOf(staff);
  assert.match(owner.cookies.join(';'), /HttpOnly/); assert.match(owner.cookies.join(';'), /SameSite=Strict/);
  assert.equal(owner.data.user.passwordHash, undefined);
  assert.equal((await call('/api/dispatches', 'GET', undefined, staffCookie)).status, 200);
  assert.equal((await call('/api/auth/users', 'GET', undefined, staffCookie)).status, 403);
  assert.equal((await call('/api/auth/users/' + owner.data.user._id, 'PATCH', { role: 'Dispatcher', active: false }, ownerCookie)).status, 400);
  assert.equal((await call('/api/auth/users/' + staff.data.user._id, 'PATCH', { role: 'Yard Manager', active: true }, ownerCookie)).status, 200);
  assert.equal((await call('/api/dispatches', 'GET', undefined, staffCookie)).status, 200);
  assert.equal((await call('/api/master-settings/unit_04/profile', 'PUT', { businessName: 'Forbidden' }, staffCookie)).status, 403);
  assert.equal((await call('/api/dispatches/000000000000000000000000/finalize', 'POST', undefined, staffCookie)).status, 403);
  assert.equal((await call('/api/dispatches/000000000000000000000000/status', 'PATCH', { status: 'Delivered' }, staffCookie)).status, 403);
  assert.equal((await call('/api/auth/login', 'POST', { email: staff.data.user.email, password: 'incorrect password' })).status, 401);
  const secondLogin = await call('/api/auth/login', 'POST', { email: staff.data.user.email.toUpperCase(), password });
  assert.equal(secondLogin.status, 200);
  const otherSession = cookieOf(secondLogin);
  const newPassword = randomBytes(18).toString('hex');
  const changed = await call('/api/auth/password', 'POST', { currentPassword: password, password: newPassword }, staffCookie);
  assert.equal(changed.status, 200); staffCookie = cookieOf(changed);
  assert.equal((await call('/api/auth/me', 'GET', undefined, otherSession)).status, 401);
  await call('/api/auth/users/' + staff.data.user._id, 'PATCH', { role: 'Dispatcher', active: false }, ownerCookie);
  assert.equal((await call('/api/dispatches', 'GET', undefined, staffCookie)).status, 401);
  await prisma.session.updateMany({ where: { userId: owner.data.user._id }, data: { expiresAt: new Date(0) } });
  assert.equal((await call('/api/dispatches', 'GET', undefined, ownerCookie)).status, 401);
  const login = await call('/api/auth/login', 'POST', { email: owner.data.user.email, password });
  const finalCookie = cookieOf(login);
  assert.equal((await call('/api/auth/logout', 'POST', undefined, finalCookie)).status, 200);
  assert.equal((await call('/api/auth/me', 'GET', undefined, finalCookie)).status, 401);
  let last;
  for (let i = 0; i < 21; i++) last = await call('/api/auth/login', 'POST', { email: 'missing@example.test', password });
  assert.equal(last.status, 429);
});
