const test = require('node:test');
const assert = require('node:assert/strict');
const mongoose = require('mongoose');
const http = require('node:http');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const sharp = require('sharp');

test('pilot setup, upload, draft retries, finalization and historical bills', async t => {
  process.env.NODE_ENV = 'test';
  const uploadDir = await fs.mkdtemp(path.join(os.tmpdir(), 'granitesync-logos-'));
  process.env.UPLOAD_DIR = uploadDir;
  const app = require('../server');
  const Dispatch = require('../models/Dispatch');
  const Settings = require('../models/MasterSettings');
  await mongoose.connect('mongodb://127.0.0.1:27017/granitesync_pilot_test', { serverSelectionTimeoutMS: 5000 });
  const server = http.createServer(app);
  t.after(async () => { await new Promise(resolve => server.close(resolve)); await mongoose.connection.dropDatabase(); await mongoose.disconnect(); await fs.rm(uploadDir, { recursive: true, force: true }); });
  await mongoose.connection.dropDatabase();
  await Dispatch.init(); await Settings.init();
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  const settingsPath = '/api/master-settings/unit_04';
  async function call(method, route, body, mime) {
    const response = await fetch(base + route, { method, headers: { 'Content-Type': mime || 'application/json' }, body: body === undefined ? undefined : mime ? body : JSON.stringify(body) });
    return { status: response.status, data: await response.json() };
  }
  assert.equal((await call('GET', settingsPath)).data.defaultRoyaltyFee, 0);
  assert.equal((await call('PUT', settingsPath + '/profile', { businessName: ' ' })).status, 400);
  assert.equal((await call('PUT', settingsPath + '/profile', { businessName: 'Original Business', address: 'Kadapa', phone: '123' })).status, 200);
  assert.equal((await call('POST', settingsPath + '/stone-rates', { stoneType: 'Stone', finish: 'Polished', defaultRate: 40.5 })).status, 200);
  const logo = await sharp({ create: { width: 20, height: 20, channels: 3, background: '#115e59' } }).png().toBuffer();
  const uploaded = await call('POST', settingsPath + '/logo', logo, 'image/png');
  assert.equal(uploaded.status, 200);
  assert.equal((await fetch(base + uploaded.data.logoPath)).status, 200);
  assert.equal((await call('POST', settingsPath + '/logo', Buffer.from('fake'), 'image/png')).status, 400);
  assert.equal((await call('POST', settingsPath + '/logo', logo, 'image/jpeg')).status, 400);
  assert.equal((await call('POST', settingsPath + '/logo', Buffer.alloc(2 * 1024 * 1024 + 1), 'image/png')).status, 413);
  const body = { clientRequestId: 'pilot-request-123', partyName: 'Buyer', supervisor: 'Siva', logistics: { truckNumber: 'ap01', buyerDestination: 'Kadapa' }, loadingAndRoyaltyFees: 50, inventory: [{ stoneType: 'Stone', finish: 'Polished', ratePerSqFt: 40.5, measurementRows: [{ lengthFt: 3, widthFt: 2, quantity: 19, category: 'Regular', sqFt: 1, lineTotal: 1 }, { lengthFt: 3.5, widthFt: 1.5, quantity: 10, category: 'TOP' }], lineTotal: 1 }], summary: { netBillableAmount: 1 } };
  const created = await call('POST', '/api/dispatches', body);
  assert.equal(created.status, 200);
  const id = created.data._id;
  assert.equal(created.data.inventory[0].totalSqFt, 166.5);
  assert.equal(created.data.summary.netBillableAmount, 6793.25);
  const repeated = await Promise.all([call('POST', '/api/dispatches', body), call('POST', '/api/dispatches', body)]);
  assert.ok(repeated.every(result => result.data._id === id));
  assert.equal(await Dispatch.countDocuments(), 1);
  assert.equal((await call('PUT', `/api/dispatches/${id}`, { ...body, loadingAndRoyaltyFees: -1 })).status, 400);
  assert.equal((await call('PUT', `/api/dispatches/${id}`, { ...body, partyName: '' })).status, 400);
  assert.equal((await call('PUT', `/api/dispatches/${id}`, { ...body, loadingAndRoyaltyFees: 100 })).data.summary.netBillableAmount, 6843.25);
  const finalized = await call('POST', `/api/dispatches/${id}/finalize`);
  assert.equal(finalized.data.status, 'Dispatched');
  assert.equal(finalized.data.businessSnapshot.businessName, 'Original Business');
  assert.match(finalized.data.businessSnapshot.logoDataUrl, /^data:image\/png;base64,/);
  await call('PUT', settingsPath + '/profile', { businessName: 'Changed Business', removeLogo: true, defaultRoyaltyFee: 999 });
  const rateId = uploaded.data.stoneRates[0]._id;
  assert.equal((await call('PUT', `${settingsPath}/stone-rates/${rateId}`, { stoneType: 'Renamed Stone', finish: 'Honed', defaultRate: 99 })).status, 200);
  assert.equal((await call('PUT', `/api/dispatches/${id}`, body)).status, 400);
  const historical = (await call('POST', `/api/dispatches/${id}/finalize`)).data;
  assert.deepEqual(historical.summary, finalized.data.summary);
  assert.deepEqual(historical.businessSnapshot, finalized.data.businessSnapshot);
  assert.equal(historical.inventory[0].stoneType, 'Stone');
  assert.equal((await call('GET', '/api/dispatches')).data.length, 1);
});
